#!/bin/bash
# =============================================================================
# bootstrap/user-data.sh — EC2 Node Bootstrap Script
#
# Description: Runs automatically when an EC2 instance launches.
#              Installs all dependencies, clones the repo, configures
#              environment variables, and installs the cron schedule.
#
# Usage: Paste the contents of this file into the EC2 Launch Wizard
#        under "Advanced Details → User Data" when launching an instance.
#
# Scales to 100+ nodes: every new EC2 with this User Data is fully
# configured automatically — zero manual setup required.
#
# Logs: /var/log/user-data.log
# =============================================================================

set -euo pipefail

LOG_FILE="/var/log/user-data.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ===== Bootstrap started ====="

# -----------------------------------------------------------------------------
# CONFIGURATION — Update these before launching your instances
# -----------------------------------------------------------------------------
GITHUB_REPO="https://github.com/YOUR_USERNAME/devops-p1-linux-automation.git"
PROJECT_DIR="/home/ubuntu/devops-p1-linux-automation"
APP_USER="ubuntu"

# S3 and alerting config — these become the .env on each node
S3_BUCKET="your-devops-logs-bucket-name"
S3_METRICS_PREFIX="metrics"
AWS_REGION="ap-southeast-2"
SLACK_WEBHOOK_URL="https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
CPU_THRESHOLD="80"
MEM_THRESHOLD="80"
DISK_THRESHOLD="85"

# -----------------------------------------------------------------------------
# Step 1 — System updates and dependencies
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Installing system packages..."
apt-get update -y
apt-get install -y \
  git \
  curl \
  awscli \
  python3 \
  python3-pip \
  python3-venv \
  jq

echo "[$(date '+%Y-%m-%d %H:%M:%S')] System packages installed."

# -----------------------------------------------------------------------------
# Step 2 — Clone the repository
# Note: If repo is private, use a GitHub PAT or deploy key here
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Cloning repository..."

if [[ -d "$PROJECT_DIR" ]]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Repo already exists — pulling latest..."
  cd "$PROJECT_DIR" && git pull
else
  git clone "$GITHUB_REPO" "$PROJECT_DIR"
fi

chown -R "$APP_USER:$APP_USER" "$PROJECT_DIR"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Repository ready at $PROJECT_DIR"

# -----------------------------------------------------------------------------
# Step 3 — Write the .env file from User Data variables
#
# This is the key to zero-touch scaling:
# You set the config here once, and every node gets identical config.
# In production, you'd pull these from AWS Secrets Manager instead.
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Writing config/.env..."

mkdir -p "$PROJECT_DIR/config"
cat > "$PROJECT_DIR/config/.env" <<EOF
# Auto-generated by user-data.sh on $(date)
# Do not edit manually — update user-data.sh and re-launch

SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}

CPU_THRESHOLD=${CPU_THRESHOLD}
MEM_THRESHOLD=${MEM_THRESHOLD}
DISK_THRESHOLD=${DISK_THRESHOLD}

MAX_LOG_SIZE_MB=10
LOG_RETAIN_DAYS=30

S3_BUCKET=${S3_BUCKET}
S3_METRICS_PREFIX=${S3_METRICS_PREFIX}
ARCHIVE_DAYS=7
AWS_REGION=${AWS_REGION}
EOF

chown "$APP_USER:$APP_USER" "$PROJECT_DIR/config/.env"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] config/.env written."

# -----------------------------------------------------------------------------
# Step 4 — Make all scripts executable
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Setting script permissions..."
chmod +x "$PROJECT_DIR/scripts/"*.sh
chmod +x "$PROJECT_DIR/security/"*.sh
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Permissions set."

# -----------------------------------------------------------------------------
# Step 5 — Create logs directory
# -----------------------------------------------------------------------------
mkdir -p "$PROJECT_DIR/logs"
chown -R "$APP_USER:$APP_USER" "$PROJECT_DIR/logs"

# -----------------------------------------------------------------------------
# Step 6 — Install cron jobs for the app user
#
# `crontab -u ubuntu` installs the cron for the ubuntu user (not root)
# This is important — cron jobs run as the user who owns them,
# and the ubuntu user has the IAM role permissions via instance metadata.
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Installing cron jobs..."

crontab -u "$APP_USER" - <<CRON
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Monitor every 5 minutes
*/5 * * * * ${PROJECT_DIR}/scripts/monitor.sh >> ${PROJECT_DIR}/logs/cron.log 2>&1

# Rotate logs daily at midnight
0 0 * * * ${PROJECT_DIR}/scripts/log-rotate.sh >> ${PROJECT_DIR}/logs/cron.log 2>&1

# Archive to S3 every Sunday at 2am
0 2 * * 0 ${PROJECT_DIR}/scripts/archive-s3.sh >> ${PROJECT_DIR}/logs/cron.log 2>&1
CRON

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Cron jobs installed."

# -----------------------------------------------------------------------------
# Step 7 — Run monitor.sh once immediately so the dashboard sees this node
#          right away (don't wait 5 minutes for first cron run)
# -----------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Running initial monitor check..."
sudo -u "$APP_USER" "$PROJECT_DIR/scripts/monitor.sh" || true
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Initial monitor check complete."

# -----------------------------------------------------------------------------
# Step 8 — Write a node-info tag file for debugging
# -----------------------------------------------------------------------------
cat > "$PROJECT_DIR/node-info.txt" <<EOF
Hostname:     $(hostname)
Instance ID:  $(curl -s http://169.254.169.254/latest/meta-data/instance-id 2>/dev/null || echo 'N/A')
Region:       ${AWS_REGION}
Bootstrapped: $(date)
Repo:         ${GITHUB_REPO}
EOF

echo "[$(date '+%Y-%m-%d %H:%M:%S')] ===== Bootstrap complete ====="
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Node is ready and reporting to S3."
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Log file: $LOG_FILE"
